/* Verilog module instantiation template generated by SCUBA Diamond_1.0_Production (529) */
/* Module Version: 5.2 */
/* Mon Oct  4 20:27:16 2010 */

/* parameterized module instance */
pll __ (.CLK( ), .CLKOP( ), .CLKOK( ), .LOCK( ));
